######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 13 11:34:49 2013
######################################################################

TEMPLATE = app
TARGET = lczGoToCell
#DESTDIR = D:/study/QtStudyBuild

DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += gotocelldialog.cpp main.cpp
